### ISSUE TITLE
1-1 introduction/basic 번역

### ISSUE THREAD

**Issue by voyagerwoo** [awskrug/eks-workshop#1]
https://github.com/awskrug/eks-workshop/tree/master/content-kr/introduction/basics

**Comment by yunsu246** [comment]
제가 하겠습니다.

**Comment by voyagerwoo** [comment]
네 감사합니다. collaborator에 추가했습니다. 확인해서 수락부탁드립니다.

**Comment by voyagerwoo** [comment]
⚠️ PR 만드실때 base repository를 awskrug로 해주세요 ㅎㅎ
![image](https://user-images.githubusercontent.com/1849824/54475082-a4ade280-4830-11e9-8669-14c61ae5e07e.png)

**Comment by yunsu246** [comment]
>  PR 만드실때 base repository를 awskrug로 해주세요 ㅎㅎ

넵넵 주의하겠습니다^-^!
