### ISSUE TITLE
3 eksctl 번역

### ISSUE THREAD

**Issue by voyagerwoo** [awskrug/eks-workshop#6]
https://github.com/awskrug/eks-workshop/tree/master/content-kr/eksctl

**Comment by leehaesung** [comment]
제가 하겠습니다.

**Comment by voyagerwoo** [comment]
네 감사합니다 ㅎㅎ

**Comment by voyagerwoo** [comment]
@leehaesung 내일 헨즈온 일정 때문에 제가 번역하겠습니다.

**Comment by leehaesung** [comment]
제가 번역한것만 보내드릴까요?

**Comment by voyagerwoo** [comment]
아 작업하신게 있으시군요 :cry:  제가 이미 다 해서 PR 확인해주시면 감사하겠습니다!
https://github.com/awskrug/eks-workshop/pull/18

**Comment by leehaesung** [comment]
마지막페이지만 못했습니다. 마주도와드릴게요

**Comment by leehaesung** [comment]
네 알겠습니다
